version: "3.4"

services:
  kafka-ui:
    container_name: data-bus-kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_started
      zookeeper:
        condition: service_started
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
  zookeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: data-bus-zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped
  kafka:
    image: bitnami/kafka:3.3.1
    container_name: data-bus-kafka
#    networks:
#      - app-tier
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: unless-stopped
    depends_on:
      - zookeeper